/**
 * @module pr-annotator
 * @description Posts Latch attestation receipts as GitHub PR comments.
 *
 * Parses PR URLs, formats receipt data as a Markdown comment,
 * and posts via the GitHub REST API.
 */

import type { SessionReceipt } from '../../types'

export interface PrUrlParts {
  owner: string
  repo: string
  prNumber: number
}

/** Parse a GitHub PR URL into owner/repo/number. */
export function parsePrUrl(url: string): PrUrlParts | null {
  try {
    const parsed = new URL(url)
    if (parsed.hostname !== 'github.com') return null
    const match = parsed.pathname.match(/^\/([^/]+)\/([^/]+)\/pull\/(\d+)/)
    if (!match) return null
    return { owner: match[1], repo: match[2], prNumber: parseInt(match[3], 10) }
  } catch {
    return null
  }
}

/** URL shown in the PR comment footer. Override via LATCH_REPO_URL env var. */
const LATCH_REPO_URL = process.env.LATCH_REPO_URL ?? 'https://github.com/anthropics/latch'

/** Format a session receipt as a GitHub PR comment body (Markdown). */
export function formatReceiptComment(receipt: SessionReceipt): string {
  const duration = Math.round(
    (new Date(receipt.enclave.endedAt).getTime() - new Date(receipt.enclave.startedAt).getTime()) / 1000,
  )

  return `## Latch Attestation

This PR was created under Latch policy **\`${receipt.policy.id}\`**, tier **\`${receipt.policy.maxDataTier}\`**.

| Metric | Value |
|--------|-------|
| Network requests | ${receipt.activity.networkRequests} |
| Blocked requests | ${receipt.activity.blockedRequests} |
| Redactions applied | ${receipt.activity.redactionsApplied} |
| Tokenizations applied | ${receipt.activity.tokenizationsApplied} |
| Tool calls | ${receipt.activity.toolCalls} |
| Tool denials | ${receipt.activity.toolDenials} |
| Sandbox | ${receipt.enclave.sandboxType} |
| Duration | ${duration}s |
| Exit | ${receipt.enclave.exitReason} |

<details>
<summary>Cryptographic proof</summary>

- **Merkle root:** \`${receipt.proof.merkleRoot}\`
- **Audit events:** ${receipt.proof.auditEventCount}
- **Signature:** \`${receipt.proof.signature.slice(0, 24)}...\`
- **Public key:** \`${receipt.proof.publicKey.slice(0, 40)}...\`

</details>

---
*Generated by [Latch Desktop](${LATCH_REPO_URL})*`
}

/**
 * Post an attestation comment on a GitHub PR.
 * Uses the GitHub REST API (no SDK dependency).
 */
export async function annotatePR(
  receipt: SessionReceipt,
  prUrl: string,
  githubToken: string,
): Promise<{ ok: boolean; commentUrl?: string; error?: string }> {
  const parts = parsePrUrl(prUrl)
  if (!parts) return { ok: false, error: `Invalid GitHub PR URL: ${prUrl}` }

  const body = formatReceiptComment(receipt)
  const apiUrl = `https://api.github.com/repos/${parts.owner}/${parts.repo}/issues/${parts.prNumber}/comments`

  try {
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({ body }),
    })

    if (!response.ok) {
      const text = await response.text()
      return { ok: false, error: `GitHub API ${response.status}: ${text}` }
    }

    const data = await response.json() as { html_url?: string }
    return { ok: true, commentUrl: data.html_url }
  } catch (err: unknown) {
    return { ok: false, error: `GitHub API error: ${err instanceof Error ? err.message : String(err)}` }
  }
}
