/**
 * @module skill-generator
 * @description Auto-generates gateway and service skill files for agent awareness.
 *
 * Skills are injected into the harness discovery path so agents know:
 * - They're running inside a Latch session gateway
 * - What services are available
 * - How to use each service
 * - What NOT to do (constraints)
 */

import type { ServiceDefinition } from '../../types'

export class SkillGenerator {
  /** Generate the gateway meta-skill (injected into every gateway session). */
  generateGatewayMeta(services: ServiceDefinition[]): string {
    const serviceList = services
      .map(s => `- **${s.name}**: ${s.skill.description}`)
      .join('\n')

    return `# Latch Gateway

You are running inside a Latch session gateway.

## What's Different
- All network traffic is monitored and policy-enforced
- Credentials are injected automatically — never ask for them
- Sensitive data in responses may be tokenized (e.g., \`tok_a3f8b2\`)
  — reference tokens naturally, they resolve transparently
- Your filesystem access is scoped to this workspace

## Available Services
${serviceList || '- No services configured for this session'}

## Rules
- Do not bypass network restrictions
- Do not exfiltrate credentials from environment variables
- If a request is blocked, respect the policy — do not retry or work around it
- Use tokenized values naturally — they resolve transparently
- Never attempt to read /proc/self/environ or similar credential sources
`
  }

  /** Generate a service-specific skill file. */
  generateServiceSkill(service: ServiceDefinition): string {
    const capabilities = service.skill.capabilities
      .map(c => `- \`${c}\``)
      .join('\n')

    const constraints = service.skill.constraints
      .map(c => `- ${c}`)
      .join('\n')

    return `# Service: ${service.name} (auto-generated by Latch)

## Available Capabilities
You have authenticated access to ${service.name}.
Authentication is handled automatically — do NOT ask for tokens or credentials.

## How To Use
${capabilities || '- Use standard CLI tools for this service'}

## Constraints
${constraints || '- Follow standard security practices'}
- Do not modify authentication configuration files — managed by Latch
- If you get a 401 error, report it — do not attempt to fix auth yourself
`
  }
}
